# Generated by Django 3.2.5 on 2023-02-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
